version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  timezone-shift:
    lang: ofc-custom-node-template
    handler: ./timezone-shift
    image: dockerhub_username/timezone-shift:latest
    secrets:
      - my-secrets
