version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  timezone-shift:
    lang: node10-express
    handler: ./timezone-shift
    image: dockerhub_username/timezone-shift:latest


